### Reference
https://cyc1am3n.github.io/2018/09/13/how-to-use-dataset-in-tensorflow.html

In [2]:
import tensorflow as tf
import numpy as np

### Generate & Initailize data

In [4]:
x = np.random.sample((100,2))
print(x)

[[0.78956841 0.04945469]
 [0.40970237 0.17166878]
 [0.20037212 0.19184105]
 [0.54451392 0.47378585]
 [0.07690661 0.03934223]
 [0.69667067 0.39097359]
 [0.86204393 0.40017681]
 [0.15762902 0.96215774]
 [0.30859904 0.2765723 ]
 [0.75272889 0.1176572 ]
 [0.74886932 0.30507981]
 [0.85427441 0.88508983]
 [0.99854475 0.75714267]
 [0.13663969 0.00336355]
 [0.62072814 0.86337777]
 [0.00867058 0.88946797]
 [0.39178852 0.58908602]
 [0.87404929 0.94596911]
 [0.10711857 0.57572191]
 [0.74273609 0.72270702]
 [0.63241848 0.46396164]
 [0.89946557 0.8260645 ]
 [0.00167916 0.52668302]
 [0.7628376  0.39403839]
 [0.09317993 0.48685186]
 [0.24727244 0.93222483]
 [0.10807784 0.32422863]
 [0.7887526  0.34491802]
 [0.19707337 0.72585477]
 [0.53708565 0.02270507]
 [0.57132305 0.23207651]
 [0.76216763 0.91833989]
 [0.16805704 0.61416375]
 [0.43835818 0.84323244]
 [0.26820556 0.89943497]
 [0.83773569 0.32726014]
 [0.42541342 0.39310915]
 [0.29304101 0.61901203]
 [0.70877798 0.95054478]
 [0.04074097 0.99289251]


In [5]:
dataset = tf.data.Dataset.from_tensor_slices(x)

### Generate & Initailize fetures & labels

In [7]:
features, labels = (np.random.sample((100,2)), np.random.sample((100,1)))
print("features: \n", features)

features: 
 [[0.00703451 0.79067886]
 [0.17663263 0.72258023]
 [0.6936106  0.18132885]
 [0.02554335 0.39976228]
 [0.11659932 0.95984856]
 [0.77253315 0.92629954]
 [0.66791416 0.86197602]
 [0.05958787 0.00678802]
 [0.28475345 0.50366661]
 [0.18823894 0.523541  ]
 [0.79297879 0.91340331]
 [0.51241992 0.09496469]
 [0.67165824 0.56791339]
 [0.08634682 0.06329314]
 [0.33901754 0.35663783]
 [0.12866543 0.01353634]
 [0.65595756 0.56484907]
 [0.28730348 0.79756401]
 [0.61740658 0.38946324]
 [0.36372162 0.84166378]
 [0.43013374 0.866301  ]
 [0.18983886 0.53198638]
 [0.24152428 0.85250027]
 [0.98979688 0.74442837]
 [0.51841508 0.82496781]
 [0.90673053 0.92354822]
 [0.99579794 0.51474624]
 [0.96549516 0.50496986]
 [0.70998634 0.82741611]
 [0.32686374 0.80927623]
 [0.64335574 0.62393015]
 [0.21931299 0.14405269]
 [0.39553549 0.01607543]
 [0.03395492 0.64084831]
 [0.97995496 0.80072283]
 [0.23979867 0.82603755]
 [0.20531865 0.75635052]
 [0.29271129 0.93208589]
 [0.00365798 0.12411837]
 [0.65773921 

In [8]:
print("labels: \n", labels)

labels: 
 [[0.38574839]
 [0.6926771 ]
 [0.4165407 ]
 [0.4153857 ]
 [0.71942452]
 [0.65625272]
 [0.04251592]
 [0.34854037]
 [0.36305745]
 [0.25914876]
 [0.23566393]
 [0.4581935 ]
 [0.32156716]
 [0.95634435]
 [0.87638764]
 [0.38662097]
 [0.3771355 ]
 [0.97461186]
 [0.72005371]
 [0.59487888]
 [0.63419435]
 [0.90596559]
 [0.25217722]
 [0.84164565]
 [0.8485473 ]
 [0.98448235]
 [0.37008815]
 [0.07116618]
 [0.19013257]
 [0.47240145]
 [0.22253211]
 [0.00147173]
 [0.32561675]
 [0.01221052]
 [0.70533895]
 [0.60669437]
 [0.72272148]
 [0.48835403]
 [0.24586636]
 [0.1942466 ]
 [0.06109328]
 [0.21657139]
 [0.88778143]
 [0.6126912 ]
 [0.41181619]
 [0.31361243]
 [0.25428926]
 [0.99960675]
 [0.658883  ]
 [0.98143227]
 [0.94267097]
 [0.82051234]
 [0.05917975]
 [0.63967319]
 [0.05083091]
 [0.29672359]
 [0.65695513]
 [0.4668372 ]
 [0.61168643]
 [0.9929951 ]
 [0.2458401 ]
 [0.34679861]
 [0.33865926]
 [0.66249701]
 [0.98395643]
 [0.39489423]
 [0.97794662]
 [0.85561214]
 [0.73378343]
 [0.67233067]
 [0.789338

In [9]:
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

In [12]:
sess = tf.Session()

(array([0.00703451, 0.79067886]), array([0.38574839]))


In [14]:
# Print iterable element
print(sess.run(next_element))

(array([0.6936106 , 0.18132885]), array([0.4165407]))


In [15]:
sess.close()

### Load placeholder

In [16]:
x = tf.placeholder(tf.float32, shape=[None, 2])
dataset = tf.data.Dataset.from_tensor_slices(x)

### Using generater initialize dataset

In [19]:
sequence = np.array([[[1]],[[2],[3]],[[3],[4],[5]]])
print(sequence)
print(sequence.shape)

[list([[1]]) list([[2], [3]]) list([[3], [4], [5]])]
(3,)


In [21]:
def generator():
    for el in sequence:
        yield el

In [28]:
dataset = tf.data.Dataset.from_generator(generator,
                                         output_types= tf.int64,
                                         output_shapes=(tf.TensorShape([None, 1])))

Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    


In [29]:
iter = dataset.make_initializable_iterator()
el = iter.get_next()

Instructions for updating:
Colocations handled automatically by placer.


In [31]:
with tf.Session() as sess:
    sess.run(iter.initializer)
    print("1:\n", sess.run(el))
    print("2:\n", sess.run(el))
    print("3:\n", sess.run(el))

1:
 [[1]]
2:
 [[2]
 [3]]
3:
 [[3]
 [4]
 [5]]


### Load csv file

###### THIS FUNCTION IS DEPRECATED

In [50]:
CSV_PATH = "./data.csv"
# THIS FUNCTION IS DEPRECATED
dataset = tf.contrib.data.make_csv_dataset(CSV_PATH, batch_size=1)

In [51]:
print(dataset)

<DatasetV1Adapter shapes: OrderedDict([(a, (1,)), (b, (1,)), (c, (1,)), (d, (1,)), (e, (1,))]), types: OrderedDict([(a, tf.int32), (b, tf.int32), (c, tf.int32), (d, tf.int32), (e, tf.int32)])>


In [39]:
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

In [57]:
print(next_element)

OrderedDict([('a', <tf.Tensor 'IteratorGetNext_3:0' shape=(1,) dtype=int32>), ('b', <tf.Tensor 'IteratorGetNext_3:1' shape=(1,) dtype=int32>), ('c', <tf.Tensor 'IteratorGetNext_3:2' shape=(1,) dtype=int32>), ('d', <tf.Tensor 'IteratorGetNext_3:3' shape=(1,) dtype=int32>), ('e', <tf.Tensor 'IteratorGetNext_3:4' shape=(1,) dtype=int32>)])


In [56]:
inputs = next_element['a']

In [58]:
print(inputs)

Tensor("IteratorGetNext_3:0", shape=(1,), dtype=int32)


###### THIS FUNCTION IS NEW

In [195]:
# THIS FUNCTION IS NEW
dataset_test = tf.data.experimental.make_csv_dataset(CSV_PATH, batch_size=1,
                                                    column_names=["feather", 'wing', 'chapter'],
                                                    column_defaults=[tf.float32, tf.float32, tf.float32],
                                                    label_name="chapter")

In [196]:
print(dataset_test)

<DatasetV1Adapter shapes: (OrderedDict([(feather, (1,)), (wing, (1,))]), (1,)), types: (OrderedDict([(feather, tf.float32), (wing, tf.float32)]), tf.float32)>


In [197]:
iterator_test = dataset_test.make_one_shot_iterator()
next_element_test = iterator_test.get_next()

In [198]:
print(next_element_test)

(OrderedDict([('feather', <tf.Tensor 'IteratorGetNext_7:0' shape=(1,) dtype=float32>), ('wing', <tf.Tensor 'IteratorGetNext_7:1' shape=(1,) dtype=float32>)]), <tf.Tensor 'IteratorGetNext_7:2' shape=(1,) dtype=float32>)


In [199]:
inputs, labels = next_element_test

In [200]:
print(inputs)

OrderedDict([('feather', <tf.Tensor 'IteratorGetNext_7:0' shape=(1,) dtype=float32>), ('wing', <tf.Tensor 'IteratorGetNext_7:1' shape=(1,) dtype=float32>)])


In [201]:
print(labels)

Tensor("IteratorGetNext_7:2", shape=(1,), dtype=float32)


In [202]:
with tf.Session() as sess:
    sess.run(next_element_test)