# Classification

In [1]:
# ref https://leechanho.tistory.com/23
# ref https://github.com/golbin/TensorFlow-Tutorials/blob/master/04%20-%20Neural%20Network%20Basic/01%20-%20Classification.py
import tensorflow as tf
import numpy as np

In [2]:
x_data = np.array([[0, 0], [1, 0], [1, 1], [0, 0], [0, 0], [0, 1]])

In [3]:
y_data = np.array([[1], [2], [3], [1], [1], [3]]) - 1

In [4]:
nb_classes = 3

In [5]:
y_one_hot = tf.one_hot(y_data, nb_classes)

In [6]:
print(y_one_hot.shape)
y_one_hot = tf.reshape(y_one_hot, [-1, nb_classes])
print(y_one_hot.shape)

(6, 1, 3)
(6, 3)


In [7]:
X = tf.placeholder(tf.float32, shape=[None, 2])
# Y = tf.placeholder(tf.float32, shape=[None, 1])

In [8]:
W = tf.Variable(tf.random_uniform([2, nb_classes]))

In [9]:
b = tf.Variable(tf.random_uniform([nb_classes]))

In [10]:
L = tf.add(tf.matmul(X, W), b)

In [11]:
L = tf.nn.relu(L)

In [12]:
model = tf.nn.softmax(L)

In [13]:
cost = tf.reduce_mean(-tf.reduce_sum(y_one_hot * tf.log(model), axis=1))

In [14]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)

In [15]:
train_op = optimizer.minimize(cost)

In [16]:
# Train
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [17]:
print(sess.run(y_one_hot))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [18]:
print(x_data)

[[0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]]


In [19]:
print(y_data)

[[0]
 [1]
 [2]
 [0]
 [0]
 [2]]


In [21]:
for step in range(2100):
    sess.run(train_op, feed_dict={X: x_data})

    if (step + 1) % 100 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data}))

100 1.0299058
200 0.91880727
300 0.8300674
400 0.75662565
500 0.69437665
600 0.64073133
700 0.5939367
800 0.5527366
900 0.51619357
1000 0.48358402
1100 0.45433483
1200 0.4279832
1300 0.4041476
1400 0.38251066
1500 0.36280468
1600 0.34517503
1700 0.32925996
1800 0.31460774
1900 0.30107746
2000 0.28855005
2100 0.27692267


In [22]:
prediction = tf.argmax(model, 1)
print('예측값:', sess.run(prediction, feed_dict={X: x_data}))
print('원래값:', y_data.flatten())

예측값: [0 1 2 0 0 2]
원래값: [0 1 2 0 0 2]


In [25]:
correct_prediction = tf.equal(prediction, tf.argmax(y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print('정확도: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_data, Y: y_data}))

정확도: 100.00
